### PR TITLE
Don't dismiss PRs that have all reviews approved

### PR DESCRIPTION
**Pull request by nicolaslt**
Hello :wave: !

We're trialling this Github Action and found that when all reviews are submitted, a manual rerun of the GH action still doesn't approve this check.

As far as I understand, `requested_reviewers` is just a list of all reviewers rather than a list of reviewers that haven't yet reviewed, and so will never be empty.

Our trigger setup is the following, if it helps having context
```yaml
on:
  pull_request:
    types: [review_requested, review_request_removed]
    branches:
      - main
  pull_request_review:
    types: [submitted, dismissed]
    ```

### CODE REVIEW

**Comment by nicolaslt** [comment]
Hmm, the large change in the sourcemap is a bit unexpected.

I generated it through
```
npm ci && npm run package
```

Let me know if there's some details I've missed here.

**Comment by SnowCait** [comment]
Thanks for PR.

>As far as I understand, requested_reviewers is just a list of all reviewers rather than a list of reviewers that haven't yet reviewed, and so will never be empty.

I've tried it, but `requested_reviewers` becomes `0`.
This means `requested_reviewers` is a list of reviewers that haven't yet reviewed.
https://github.com/SnowCait/actions-sandbox/runs/5297953770?check_suite_focus=true#step:2:21
>##[debug]requested reviewers: 0
##[debug]reviews: 1

Is there any specific example that `requested_reviewers` won't be empty?
Some precondition might be missing in my test.

**Comment by nicolaslt** [comment]
Hm yeah I think I misunderstood something in how Github Action are re-ran.

I'm not sure how to use this Action successfully though but that question doesn't belong in a pull request :smile:. I'll experiment some more and if I still can't make it work to my understanding I'll open an issue for discussion if that's alright?

**Comment by SnowCait** [comment]
I found the cause.
This action uses `github.context` to get `requested_reviewers`.
https://github.com/snow-actions/unanimously-approved/blob/39a4e406b1e202d82d49e3bc93b73924b1c06dd3/src/main.ts#L9-L11
Re-run reproduce the context as same as first time, and `requested_reviewers` is never changed.

Therefore, you should not use re-run for updating check status. (on current code at least)

**Comment by SnowCait** [comment]
Hi @nicolaslt,

I released [v2.0.0](https://github.com/snow-actions/unanimously-approved/discussions/68).
Try it.

**Pull request closed without merging**
